### ISSUE TITLE
"Enter search terms" error when clicking title of book

### ISSUE THREAD

**Issue by hugolio** [scriptotek/emnesok#119]
(Applies only to FRBR-ized books)

E.g., https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011930&lang=en

First book:
- Clicking hyperlink "When the machine made art : the troubled history of computer art" (title) results in "Enter search terms" error on Oria
- Clicking hyperlink "Print copy at UiO and 2 other libraries." works fine
- Clicking hyperlink "E-book" results in "No full text available" message

**Comment by danmichaelo** [comment]
Example:

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=UBO&vid=UBO&search_scope=bibsys_ils&query=facet_frbrgroupid,exact,212831450

I don't think the syntax was ever officially documented, but it was recommended by an Ex Libris guy here:

https://developers.exlibrisgroup.com/forum/posts/list/213.page

It worked at some point, but then stopped working.. When i asked about this, I never got any answer:

https://developers.exlibrisgroup.com/forum/posts/list/382.page

The only way to fix this is probably to use the syntax you get when copying from the adress bar:

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?cs=frb&ct=frb&frbg=212831450&fctN=facet_frbrgroupid&fctV=212831450&doc=BIBSYS_ILS71536946620002201&rfnGrp=frbr&frbrSrt=date&frbrRecordsSource=Primo+Local&frbrSourceidDisplay=BIBSYS_ILS&query=facet_frbrgroupid%2Cexact%2C212831450&fn=search&search_scope=bibsys_ils&dscnt=0&scp.scps=scope%3A(BIBSYS_ILS)&vid=UBO&ct=search&institution=UBO&tab=library_catalogue&vl(freeText0)=Jeg%20pr%C3%B8ver%20%C3%A5%20finne%20rosa%20elementer,%20men%20finner%20bare%20lilla&dstmp=1483458826142&fromDL

This looks rather brittle, but for now it's better than nothing at all.
