### ISSUE TITLE
Visning av akronymer og kjemiske symboler

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/emnesok#3]
Per i dag finnes de bare som `skos:altLabel` på data.ub.uio.no, så vi må gjøre noe med RDF-konverteringen slik at vi kan skille disse ut. Avhenger av https://github.com/realfagstermer/roald/issues/3 og https://github.com/realfagstermer/roald/issues/4

**Comment by kyrretl** [comment]
I tillegg har de ikke språkattributter, lang="en" osv, vi må tenke litt
