### ISSUE TITLE
Automatisk utvide til bredere søk dersom snevert returnerer null treff

### ISSUE THREAD

**Issue by kyrretl** [scriptotek/emnesok#33]
Dette bør ikke skje ofte, for emneord skal minst ha ett objekt knyttet til seg. Men dersom vi får kasseringer kan det skje. Prøv å søke på hatcheries på snevert/bredt

**Comment by danmichaelo** [comment]
Sånn:

---

<img width="677" alt="skjermbilde 2015-12-16 kl 13 53 10" src="https://cloud.githubusercontent.com/assets/434495/11841263/5ecb5c7e-a3fc-11e5-82ff-e8a85d56d74a.png">

---

Klekkerier, [c031455](data.ub.uio.no/realfagstermer/c031455), er forresten en «ny» term sendt inn av UBB i sommer: https://github.com/realfagstermer/realfagstermer/issues/266
