### ISSUE TITLE
Bestemme seg for default-trunkering

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/emnesok#4]
Valgene står vel mellom (1) kun høyretrunkering eller (2) både venstre- og høyretrunkering.

Venstre-trunkering gir selvfølgelig flere resultater, men dermed også mer støy. Søk etter "hester" med venstretrunkering fører f.eks. til at de mest relevante treffene kommer et stykke ned i lista.

Høyttenkning: Trefflista er sortert alfabetisk som standard. Vi _kan_ trikse med sorteringen av resultatlisten og legge eksakte treff øverst, fulgt av treff der termen _begynner med_ søketermen, og la termene med venstretrunkering komme til slutt. Men det kan skape forvirring det også..

**Comment by kyrretl** [comment]
Kanskje de termene som har fått eksakt treff kan vises med uthevet tekst. Eller kanskje det ikke trengs. Angucomplete viser uansett "trefftekst" med lyseblå farge for _hele_ termen ved eksakt treff. Vi kan avgjøre dette etter at brukertesting har gitt oss mer kjøtt på beinet
