### ISSUE TITLE
Søke på nynorsk -> vise på nynorsk?

### ISSUE THREAD

**Issue by mittinatten** [scriptotek/emnesok#46]
Gir det mening at taggene i søketreffene vises på nynorsk når en søker på nynorsk, siden vi nå har komplett oversettelse?

**Comment by danmichaelo** [comment]
Du mener i katalogsøket (den høyre delen av skjermen)? Det hadde vært veldig kult, men det dumme er jo at det ikke ligger ID-er på postene, bare termer (på bokmål). Så da må vi slå opp alle bokmålstermene og hente ut nynorsktermer. Men hvis jeg kunne sendt alle termene til serveren i en forespørsel, og slått de opp mot en _in memory cache_ burde det kunne gå kjapt nok.

**Comment by danmichaelo** [comment]
Mulig duplikat av #31

**Comment by mittinatten** [comment]
Ja, riktig, det bli vel duplikat ja, så ikke den.

Skjønner utfordringen med ID-ene, men en internt lagret oversettelsestabell høres ut som en ok løsning. (Nå er jeg ikk insatt i teknologien dere bruker i det hele tatt).

**Comment by danmichaelo** [comment]
Lukker som duplikat av #31
